create table if not exists public.kopken_catalog_snapshots (
  id bigint generated by default as identity primary key,
  outlet_code text not null,
  outlet_name text not null,
  outlet_address text,
  category text not null,
  menu jsonb not null default '[]'::jsonb,
  source text not null default 'vsphone_official_app',
  status text not null default 'ready'
    check (status in ('needs_review', 'ready', 'archived')),
  captured_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_code, category)
);

alter table public.kopken_catalog_snapshots enable row level security;

revoke all on table public.kopken_catalog_snapshots from anon, authenticated;
grant select on table public.kopken_catalog_snapshots to anon, authenticated;

drop policy if exists "Public can read ready Kopken catalog snapshots"
  on public.kopken_catalog_snapshots;

create policy "Public can read ready Kopken catalog snapshots"
on public.kopken_catalog_snapshots
for select
to anon, authenticated
using (status = 'ready');
